# .pre-commit-config.yaml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0
    hooks:
      - id: prettier

  - repo: local
    hooks:
      - id: frontend-lint
        name: Frontend ESLint
        entry: docker-compose exec -T client npm run lint
        language: system
        files: ^client/.*\.(js|jsx|ts|tsx)$
        pass_filenames: false

      - id: frontend-types
        name: Frontend Type Check
        entry: docker-compose exec -T client npm run type-check
        language: system
        files: ^client/.*\.(ts|tsx)$
        pass_filenames: false
