import type { Metadata } from "next";
import localFont from "next/font/local";
import "../globals.css";

import { Input } from "@/components/ui/input"
import { SidebarNav } from "@/components/ui/navigation";
import { ChatsSidebar } from "@/components/ui/chatsSidebar";
import { Header } from "@/components/ui/header";

const geistSans = localFont({
  src: ".././fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: ".././fonts/GeistMonoVF.woff", 
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="flex h-screen">

          <aside className="w-16 bg-white border-r border-gray-200">
            <div className="h-16 flex items-center justify-center">
              <img className="w-16 h-11 rounded-full" src="https://i.fbcd.co/products/resized/resized-750-500/d4c961732ba6ec52c0bbde63c9cb9e5dd6593826ee788080599f68920224e27d.jpg" alt="Rounded avatar" />
            </div>  
            <SidebarNav /> 
          </aside>

          <ChatsSidebar /> 

          <div className="flex-1 flex flex-col">
            <Header />

            <main className="flex-1 overflow-auto p-6">
              {children}
            </main>
            
          </div>
        </div>
      </body>
    </html>
  );
}